version: '3.8'
services:
  redis:
    image: redis:latest
    privileged: true
    user: root
    ports:
     - 6379:6379
    container_name: redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
  voteapp:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      REDIS: redis
